name: Delete PR App Service Slot

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deleting PR#${{ github.event.number }}"
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Delete PR Slot
      run: |
        az account set -s ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az webapp deployment slot delete --name AdvancedActions --resource-group .NETConf --slot "pr-${{ github.event.number }}"