name: Build and deploy to AdvancedActions
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 5 1 * *'
env:
  AZURE_WEBAPP_NAME: AdvancedActions
  AZURE_WEBAPP_PACKAGE_PATH: AdvancedActions/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AdvancedActions_aa9e }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: AdvancedActions
jobs:
  BuildTestDeployAdvancedActions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3