name: Deploy Function App to isaac-dotnet-conf-function
on:
  push:
    branches:
    - main
    paths:
    - 'AzureFunction/**'
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_NAME: isaac-dotnet-conf-function
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./published
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.ISAAC_DOTNET_CONF_FUNCTION_PUBLISH_PROFILE }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  PROJECT_PATH: AzureFunction
jobs:
  BuildDeployFunction:
    runs-on: windows-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@master
    - name: Setup .NET Core SDK ${{ env.DOTNET_CORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore packages
      run: dotnet restore "${{ env.PROJECT_PATH }}"
    - name: Build app
      run: dotnet build "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish app for deploy
      run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Run Azure Functions Action
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
